server:
  port: 8080
app:
  file:
#    location: D:/Chipo/Admin-Angular-CRUD/src/main/resources/static/ D:/Java/OrderCom/blogs-main
#    product: ${app.file.location}/product
    url-prefix: http://localhost:${server.port}/file
  url-local:
    url: http://localhost:${server.port}

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
  datasource:
    url: jdbc:mysql://13.211.58.3:3306/orders
    username: orders
    password: 23102000
    driver-class-name: com.mysql.cj.jdbc.Driver
    maximum-pool-size: 20
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: '250'
        prepStmtCacheSqlLimit: '2048'
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  web:
    resources:
      add-mappings: true
logging:
  level:
    com:
      zaxxer:
        hikari: TRACE

